// <auto-generated />
namespace Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class QuotesAndTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuotesAndTags));
        
        string IMigrationMetadata.Id
        {
            get { return "201404150106127_QuotesAndTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
